# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START cloudbuild]
steps:
# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/web-infra-template/backend:$SHORT_SHA'
  - '.'
  dir: 'backend'

# This step pushes the image to Artifact Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/web-infra-template/backend:$SHORT_SHA'
# [END cloudbuild]

# Access the id_github file from Secret Manager
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'gcloud secrets versions access latest --secret=github-ssh-key > /builder/home/.ssh/id_github' ]
  volumes:
  - name: 'ssh'
    path: /builder/home/.ssh

# Set up git with key and domain
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 666 /builder/home/.ssh/id_github
    cat <<EOF >/builder/home/.ssh/config
    Hostname github.com
    IdentityFile /builder/home/.ssh/id_github
    EOF
    ssh-keyscan -t rsa github.com > /builder/home/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /builder/home/.ssh

# Edit Kustomize layer in config repo and push changes
- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Cloning repo ..."
    ls ~/.ssh
    git clone --depth 1 git@github.com:CyCTW/web-manifests.git
    echo "Updating image tag version ..."
    cd web-manifests/web-infra-template/base
    ls
    sed -i "s|newTag: .*|newTag: $SHORT_SHA|" kustomization.yaml
    echo "Pushing changes to git config repo ..."
    git config --global user.name cyctw
    git config --global user.email zxcvbnmichael192@gmail.com
    git add -A
    git commit -m "Updated with build ${BUILD_ID} from ${REPO_NAME} commit ${COMMIT_SHA}"
    git push origin production
  volumes:
  - name: 'ssh'
    path: /builder/home/.ssh